"""Assemble the supplied CGP sources into ROM-free, independently owned writes.

Asar is a build-time tool only. Two blank images identify every byte written,
including zeroes, without copying any bytes from a copyrighted input ROM.
"""
import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def assemble(asar, source, work, bank, text=None):
    work.mkdir(parents=True, exist_ok=True)
    wrapper = work / 'patch.asm'
    body = text if text is not None else source.read_text(encoding='cp1252')
    wrapper.write_text(f'lorom\norg ${bank:02X}8000\n' + body, encoding='utf-8', newline='\n')
    images = []
    for fill in (0x55, 0xaa):
        rom = work / f'blank-{fill}.sfc'
        blank = bytearray([fill]) * 0x400000
        blank[0x7fd9] = 1  # USA, for the source's region guard
        rom.write_bytes(blank)
        result = subprocess.run([str(asar), '--no-title-check', '--fix-checksum=off',
                                 '--pause-mode=never', str(wrapper), str(rom)],
                                capture_output=True, text=True)
        if result.returncode:
            raise ValueError(result.stdout + result.stderr)
        images.append(rom.read_bytes())
    a, b = images
    writes = []
    for offset in range(len(a)):
        if offset == 0x7fd9 or a[offset] != b[offset]:
            continue
        if writes and writes[-1][0] + len(writes[-1][1]) == offset:
            writes[-1][1].append(a[offset])
        else:
            writes.append([offset, [a[offset]]])
    return writes


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--asar', type=Path, required=True)
    p.add_argument('--work', type=Path, default=ROOT / 'captures/cgp-asm')
    args = p.parse_args()
    files = [f'CGP/{i}/{name}.asm' for name in ('CGP','CGP_Boost','CGP_Blast_Pipe') for i in (1,2,3)]
    files += ['BF_GF_Animation_Fix.asm','Dash_Fix2.asm','Dynamic_Spin_Amount.asm',
              'Lateral_Bounce_Damper.asm','Lateral_Hit_Harder_CPU_Spin.asm',
              'Lateral_Hit_Redirect_Rotation.asm','Legend_Difficulty.asm',
              'No_DMag_Damage.asm','No_Lap_Finish_on_Shortcut.asm','CGP_Illusion.asm',
              'Rainbow_Gravity.asm','redbumperfix-v2.asm','Refined_Hitbox.asm',
              'Reverse_DMAG .asm','Smooth_Fog.asm','fzedit-msu.asm','CGP_Credits.asm']
    lines = ['/* Generated by tools/build_cgp_mods.py from author-supplied ASM only. */',
             'typedef struct RuleWrite { unsigned offset, size; const uint8_t *data; } RuleWrite;',
             'typedef struct RulePatch { const RuleWrite *writes; unsigned count; } RulePatch;']
    out = {}
    for deluxe in (False, True):
        for i, key in enumerate(files):
            source = ROOT / 'mods/cgp-source' / key
            body = source.read_text(encoding='cp1252')
            if source.name == 'Legend_Difficulty.asm':
                # Opponent resource loading and menus belong to the host adapter.
                # Keep the source's race rules and tables, with a guarded helper.
                body += '\nHijack_Explosive_Frequency:\n RTL\n'
            if source.name == 'Dynamic_Spin_Amount.asm' and deluxe:
                body = body.replace('LDA $FAE5,X', 'LDA.l $7F4D60').replace('LDA $FADD,X', 'LDA.l $7F4D5E')
            if source.name == 'CGP_Boost.asm':
                # Retained for private legacy-profile oracle tests. Production
                # BS mode excludes these profiles; CGP uses four-slot cohorts.
                for label, directive in [('boost_drain','dw'),('duration_table','db')]:
                    pattern = rf'({label}:\s*{directive}\s+)([^;\n]+)'
                    body = re.sub(pattern, lambda m: m[1]+m[2].strip()+', '+m[2].strip(), body)
                body = body.replace('LDX $D1', 'PHP\n  LDA $52\n  AND #$00FF\n  ASL\n  TAX\n  PLP')
            if source.name == 'Rainbow_Gravity.asm':
                start = body.index('  LDA $90')
                end = body.index('  BNE Regular_Gravity', start)
                body = body[:start] + '  LDA $0ADF\n  CMP #$FF\n' + body[end:]
            writes = assemble(args.asar.resolve(), source, args.work / f'{int(deluxe)}-{i}', 0x30+i, body)
            omitted = set()
            if source.name == 'Legend_Difficulty.asm':
                omitted |= {0x5432,0x18819,0x1882a,0x18841,0x189e1}
            if source.name == 'CGP_Illusion.asm':
                omitted.add(0x8976-0x8000)  # Stable course ID sets IS_ILLUSION, not cup arithmetic.
            if deluxe and source.name == 'CGP.asm':
                omitted |= {0x5411,0x6335,0x7078,0x7a36}
            if deluxe and source.name == 'CGP_Blast_Pipe.asm':
                # Deluxe reads per-vehicle exhaust metadata; the host adapter
                # uses the assembled coordinate data, without replacing its callers.
                omitted |= {off for off,_ in writes if off < 0x80000}
            writes = [w for w in writes if w[0] not in omitted]
            symbol = f'rule_{int(deluxe)}_{i}'
            out[symbol] = {'source':key, 'writes':writes}
            for j, (offset, values) in enumerate(writes):
                lines.append(f'static const uint8_t {symbol}_{j}[] = {{')
                for n in range(0,len(values),24):
                    lines.append('  '+','.join(f'0x{x:02x}' for x in values[n:n+24])+',')
                lines.append('};')
            lines.append(f'static const RuleWrite {symbol}[] = {{')
            for j,(offset,values) in enumerate(writes):
                lines.append(f'  {{0x{offset:x}, {len(values)}, {symbol}_{j}}},')
            lines.append('};')
            print(symbol, key, sum(len(x[1]) for x in writes), 'bytes')
    # Every selectable combination must have reviewed byte ownership. Equal
    # overlapping writes are harmless; differing values need a known adapter.
    for deluxe in (0, 1):
        for tuning in range(3):
            for boost in range(3, 6):
                for exhaust in range(6, 9):
                    owners = {}
                    for patch in [tuning, boost, exhaust]+list(range(9, len(files))):
                        for offset, values in out[f'rule_{deluxe}_{patch}']['writes']:
                            for at, value in enumerate(values, offset):
                                if at in owners and owners[at][1] != value:
                                    previous = owners[at][0]
                                    assert previous < 3 and patch in (15, 16), (deluxe, at, previous, patch)
                                owners[at] = (patch, value)
    lines.append(f'static const RulePatch rule_patches[2][{len(files)}] = {{')
    for deluxe in (0,1):
        lines.append(' {')
        for i in range(len(files)):
            symbol=f'rule_{deluxe}_{i}'
            lines.append(f'  {{{symbol}, sizeof({symbol})/sizeof(*{symbol})}},')
        lines.append(' },')
    lines.append('};')
    msu = bytearray(0x20000)
    for off,values in out['rule_0_24']['writes']:
        msu[off:off+len(values)] = bytes(values)
    selector = msu.index(bytes.fromhex('a5462907c906d0'))
    branch = msu[selector+7]
    if branch >= 128: branch -= 256
    def snes(off): return ((off//0x8000)<<16) | (off%0x8000) | 0x8000
    lines.append(f'#define CGP_MSU_SELECTOR 0x{snes(selector):06x}u')
    lines.append(f'#define CGP_MSU_RETURN 0x{snes(selector+8+branch):06x}u')
    lines.append('static const uint8_t exhaust_counts[3][4] = {')
    exhaust = []
    for profile in range(3):
        image = bytearray(0x110000)
        for off,values in out[f'rule_0_{6+profile}']['writes']:
            image[off:off+len(values)] = bytes(values)
        counts, cars = [], []
        pointers = [0xc68c] + [int.from_bytes(image[0x3e98+i*2:0x3e9a+i*2],'little') for i in range(3)]
        for car,pc in enumerate(pointers):
            code = image[pc-0x8000:pc-0x8000+48]
            shift = 0 if code[0]==0xc2 else 2 if code[4]==0x4a else 1
            at = code.index(0xbf)
            address = int.from_bytes(code[at+1:at+4],'little')
            # P2 Wild Goose has THREE pipes and uses the 6-byte stride table.
            # Count actual sprite stores; a bit-shift heuristic loses this case.
            code = code[:code.index(0x60)]
            count = len(re.findall(rb'\x8d[\xf0\xf4\xf8\xfc]\x02', code))
            stride_table = int.from_bytes(code[3:5], 'little') if code[0]==0xc2 else 0xc76f
            start = ((address>>16)&127)*32768+(address&32767)
            counts.append(count)
            cars.append([list(image[start+(image[stride_table-0x8000+frame]>>shift):start+(image[stride_table-0x8000+frame]>>shift)+count*2])+[0]*(8-count*2) for frame in range(13)])
        exhaust.append(cars)
        lines.append(' {'+','.join(map(str,counts))+'},')
    lines.append('};\nstatic const uint8_t exhaust_positions[3][4][13][8] = {')
    for cars in exhaust:
        lines.append(' {')
        for frames in cars:
            lines.append('  {'+','.join('{'+','.join(map(str,row))+'}' for row in frames)+'},')
        lines.append(' },')
    lines.append('};')
    (ROOT/'src/fzero_gameplay_patches.inc').write_text('\n'.join(lines)+'\n',encoding='utf-8', newline='\n')
    (args.work/'writes.json').write_text(json.dumps(out),encoding='utf-8', newline='\n')
    sources = ROOT/'mods/cgp-source'
    for name in ('CGP', 'CGP_Boost', 'CGP_Blast_Pipe'):
        assert (sources/f'{name}.asm').read_bytes() == (sources/f'CGP/3/{name}.asm').read_bytes()
    index = {p.relative_to(sources).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
             for p in sorted(sources.rglob('*.asm'))}
    assert len(index) == 29
    (sources/'SOURCE_INDEX.json').write_text(json.dumps(index,indent=2)+'\n',encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
